### ISSUE TITLE
Thanks for the initiative!

### ISSUE THREAD

**Issue by blynkkk** [ilcato/homebridge-blynk#1]
Just came across your work in progress. Let us know if we can help with something.

Looking forward to starting using this plugin and spreading the word about it

**Comment by ilcato** [comment]
I'm trying to build a first usable version. Just added read support for switch. I plan to have such a version in a few days.
It could be useful to have an api on the server to look for changes in order to automatically update the homekit status. Currently the only option I have is to perform a periodic polling on all pins -> to heavy.

**Comment by doom369** [comment]
Do you mean webhook on pin change?

**Comment by ilcato** [comment]
Yes

**Comment by ilcato** [comment]
@blynkkk : how do I refer to a physical pin through the Rest API. I'm able to read and write to a virtual pin. But what is the syntax for physical one (digital and analog)? Is it D1, D2, ... and A1, A2, ... or GP1, GP2 as in the Blynk app?

**Comment by doom369** [comment]
> Is it D1, D2, ... and A1, A2

yes.

**Comment by ilcato** [comment]
@doom369 : is it correct the following behavior?
- I have a button on pin D4
- I associated it to a Value Display widget on the Blynk app with a 1 sec parameter
- the Blynk app correctly visualize the value of the pin
- if I read the same pin through the rest API I'm able to see the correct value but only if the Blynk app is running in foreground (iOs app)
  If the app is not running or is in background the API doesn't reflect the current status of the button.

If this is correct I don't think we can use Homekit.

**Comment by doom369** [comment]
Do you mean physical button? If so you need to wrap digital pin with virtual pin. And when you press physical button you need to send Blynk.virtualWrite();
Have a look in sketches we provide.

**Comment by ilcato** [comment]
This way, right?

`BLYNK_READ(V2)
  {
    int val = digitalRead(D2);
    Blynk.virtualWrite(V2, val);
  }
`

**Comment by doom369** [comment]
yes. you can also use button interrupt, so no need to have a timer on app.

**Comment by ilcato** [comment]
BLYNK_READ(V2) is called when the Blynk app is running and there's a Value Display widget associate to V2.
If I only have the REST client calling the Blynk Server for reading V2 it receives the last value polled by the app.
What I need in order to have, for example, an HomeKit accessory of type ContactSensor associated to a virtual (or physical) pin is a REST call that function without the Blynk app running.

**Comment by doom369** [comment]
https://github.com/blynkkk/blynk-library/blob/master/examples/More/ButtonInterrupt/ButtonInterrupt.ino
https://github.com/blynkkk/blynk-library/blob/master/examples/More/ButtonPoll/ButtonPoll.ino

**Comment by ilcato** [comment]
Yes, this is what I'm trying to avoid.
What I'd like to have is a mechanism similar to the one adopted for the Blynk App widget: the app calls "something on the server" and is able to retrieve the value of the pins (virtual, digital, ...).

**Comment by doom369** [comment]
This is not implemented for REST API. But you could use for this case websockets.

**Comment by ilcato** [comment]
Is there a socket entry point in Blynk server ?

**Comment by doom369** [comment]
Here is example https://github.com/blynkkk/blynk-server/tree/master/docs/websocket
and here https://github.com/tzapu/node-red-contrib-blynk-websockets

**Comment by ilcato** [comment]
I completely missed the server repository. I just downloaded the server binaries.

I will look this further info.

Thank you

**Comment by doom369** [comment]
Have fun =)

**Comment by ilcato** [comment]
@doom369, in my understanding with the script that you indicated I'm able to perform an hardware role with respect to the Blynk server. Is it right? What I'm looking for is to have the ability to execute like the Blink App in order to control the Blynk devices.

**Comment by doom369** [comment]
> Is it right?

Yes.

> What I'm looking for is to have the ability to execute like the Blink App in order to control the Blynk devices.

Could you please describe exactly and detailed use case you want to achieve? I'm afraid I don't understand your goals.

**Comment by ilcato** [comment]
Ok,
I want to be able to control Blynk hardware through HomeKit and Siri. So, for example, in order to have the ability to ask Siri something like "what's the temperature in the living room?" (provided there's a temperature sensor connected to a pin on an Arduino) I need an API on the Blynk server that allows to query the value of the pin. This is what the REST API is supposed to do I think, but in my experiment this is true only if there's the Blynk App running that polls (with the set frequency) the given pin.

**Comment by doom369** [comment]
Ok. Got it. So yes. This is true for polling and this is how polling suppose to work. Polling is application based, not server side. However it is possible to achieve what you want. All you need to do is

`Blynk.virtualWrite(V5, value);`

whenever you think it is required in your code. [Here is](https://github.com/blynkkk/blynk-library/blob/master/examples/GettingStarted/PushData/PushData.ino) a basic example of how to write value every second.

And you can call at any time HTTP GET request in order to get latest value for V5.

**Comment by ilcato** [comment]
Understood.
And what about the "-mode app" in the Java Blync client ? What is it suppose to do? Isn't it possible to go that way in order to be able to query the server the same way the Blynk app do?

**Comment by doom369** [comment]
Yes, you can do that with Blynk client, but it was designed only for integration tests in order to simulate Blynk apps. So it has no documentation, guides, etc.

**Comment by ilcato** [comment]
Ok. I will check this path. It has minor impact on the way in which you build Things.

**Comment by doom369** [comment]
Have in mind. Client will work only for local server as we use mutual SSL on Blynk Cloud.

**Comment by ilcato** [comment]
Ok. A side question, why didn't you adopt existing IoT protocol like MQTT ?

**Comment by doom369** [comment]
Few reasons :
- For application side it is absolutely unnecessary. Own protocol or websockets are much better and simpler.
- For hardware side it is a bit over engineered. It was designed for low bandwidth and for many different use cases. Blynk protocol also lightweight but much more simpler, as we don't need to cover all use cases.

We will add MQTT support for hardware side soon. But at the moment we have only few users who care about that.

**Comment by ilcato** [comment]
@doom369: it seems that the following [https://github.com/blynkkk/blynk-library/blob/master/scripts/blynk_ctrl.py](url) may be the right answer to my need.

**Comment by doom369** [comment]
Nice. Looking forward to see working prototype.

**Comment by ilcato** [comment]
@doom369: I dismiss the "bridge" approach of the blynk_ctrl.py because it present the same problem of the other approaches I test.
I switched back to the idea of implementing a client app approach on the TCP SSL entry point (the same of the Blynk app).
I was able to write a node.js module that implement the capability.
Now I have all the building blocks for completing the homebridge plugin for the HomeKit/Siri access to Blynk.

In the mean time I just published the node.js module on npm: [blynk-app-client](https://www.npmjs.com/package/blynk-app-client). It is a very first draft that I will update with the lesson learned in writing the homebridge plugin.

**Comment by doom369** [comment]
@ilcato cool. You are awesome. Thanks for sharing!

**Comment by ilcato** [comment]
@doom369: [blynk-app-client](https://www.npmjs.com/package/blynk-app-client) module is now pretty complete for my scope.

**Comment by ilcato** [comment]
@blynkkk, @doom369 : for the homekit/Siri integration I have reached a road block. Situation:
- homekit/Siri needs: an API that allows read/write access to the device pins without the Blynk mobile app running
- Option 1: the Blynk rest API (the first I tried).
  This approach fails because it requires the Blynk mobile app running
- Option 2: the TCP Hardware Socket API with a virtual Bridge component (like the blynk_ctrl.py available in blynk-library project).
  This approach fails too because it requires the Blynk mobile app running.
  The WebSocket API is similar
- Option 3: the TCP App Socket API (the same used by the Blynk mobile app).
  I wrote a node module in order to be able to access the server this way, see [blynk-app-client](https://www.npmjs.com/package/blynk-app-client)
  With this approach there's no need to have the Blynk mobile app running.
  But there's a problem with the read operation on pins that are bounded to a control widget

For example: if I have digital pin 5 connected to a Button and I try to  read its value through the hardware command, like

`blynk.hardware(101, "d", "r", 5);
`

it fails because it is looking for a FrequencyWidget connected to the same pin, that is
impossible because it is already connected to the Button Widget that is not a FrequencyWidget.

In HardwareAppLogic.java row 69 there's:

```
        case 'r' :
            FrequencyWidget frequencyWidget = dash.findReadingWidget(split[1].split(StringUtils.BODY_SEPARATOR_STRING), message.id);
            if (frequencyWidget.isTicked(split[1])) {
                session.sendMessageToHardware(ctx, dashId, new HardwareMessage(message.id, split[1]));
            }
            break;
```

If I modify the logic in:

```
        case 'r' :
            FrequencyWidget frequencyWidget = dash.findReadingWidget(split[1].split(StringUtils.BODY_SEPARATOR_STRING), message.id);
            if (frequencyWidget) frequencyWidget.isTicked(split[1]);
            session.sendMessageToHardware(ctx, dashId, new HardwareMessage(message.id, split[1]));
            break;
```

and in DashBoard.java row 104 I modify it in the following way:

from

```
    throw new IllegalCommandBodyException("No frequency widget for read command.", msgId);
```

to

```
    return null;
```

it works and it also update the LastRequestTS if necessary.

Are you able to check if this (or a similar change) is possible to introduce in the Blynk server?

Thanks.

**Comment by doom369** [comment]
> Option 1: the Blynk rest API (the first I tried).
> This approach fails because it requires the Blynk mobile app running

It doesn't. [Code](https://github.com/blynkkk/blynk-server/blob/master/server/http-api/src/main/java/cc/blynk/server/api/http/logic/HttpAPILogic.java#L77).

Suggested change is not correct from point of view of server. Button is not supposed to send reading command. The only way at the moment would be to use HTTP API.

Do you use Blynk cloud? Could you please explain why you think HTTP API doesn't work without running app?

**Comment by ilcato** [comment]
@doom369, I'm using local Blynk server.
I access digital pin number 4 with a GET request on:

`https://10.0.0.102:9443/f8fc77e07d6b415984f683ccd9bd2e4a/pin/D4`

It respond with the last value presented on widget display on the Dashboard on the mobile app when the dashboard was running.

If it is running the previous GET always respond correctly but as soon as I stop the Dashboard, put the app in the background or kill it the GET request respond with the last value read by the widget while the app was running.

I think that the reason is because in the REST API you simply return the value stored in the Widget in the Dashboard while in the App API you "sendMessageToHardware" in order to retrieve the value directly from the board. If the App is running it periodically read the value from the board and stores it in the widget.

**Comment by doom369** [comment]
What version of server do you use?

**Comment by doom369** [comment]
You are right. I'll think what we can do here.

**Comment by ilcato** [comment]
@doom369: any news?

**Comment by doom369** [comment]
Not yet. Busy with next release.

**Comment by doom369** [comment]
https://github.com/blynkkk/blynk-server/issues/118 will try to resolve it today

**Comment by ilcato** [comment]
great!

**Comment by doom369** [comment]
Also you could use `Blynk.virtualWrite` in order to set pin state to whatever you need at any moment.

**Comment by doom369** [comment]
@ilcato I spent few hours in order to find best solution, but I'm afraid implementation of such HTTP API may cause performance issues due to async nature of Blynk server. Your polling solution is only possible at the moment. I hope we will introduce WebHooks very soon so your solution may be simplified.

**Comment by ilcato** [comment]
@doom369: let me try to recap.

In order to finalize the homebridge-blynk plugin I need to have the possibility to **read and write** a pin. Consider this scenario:
- an Arduino board controls a lightbulb through a relay connected on digital pin 5
- in the homebridge plugin an HomeKit Switch is associated to the relay in order to allow a Siri command like "turn on the lamp" to be sent and transformed in to a digital write 1 to pin 5. This is currently possible.
- the plugin needs also to be able to manage Siri queries like "Is the lamp turned on ?". For this query I need to read the value of pin 5. This is not possible if I already associated the pin to a Blynk controller widget.

Please try to reconsider the change that I proposed two weeks ago that I propose as a [pull request](https://github.com/blynkkk/blynk-server/pull/119) on the Blynk server. In this way all works as I expected.

**Comment by doom369** [comment]
> the plugin needs also to be able to manage Siri queries like "Is the lamp turned on ?". For this query I need to read the value of pin 5. This is not possible if I already associated the pin to a Blynk controller widget.

This is possible if you will send Blynk.virtualWrite on pin change to server, so server will always have latest state.

**Comment by ilcato** [comment]
But this limits the scope to the virtual pins and needs to implement logic on the device side.

**Comment by doom369** [comment]
Indeed virtual pins where designed exactly for such cases. 

> and needs to implement logic on the device side.

yeah =).

I'll accept your proposal in PR and will release update soon.

**Comment by doom369** [comment]
@ilcato released [0.13.2](https://github.com/blynkkk/blynk-server/releases/tag/v0.13.2)

**Comment by ilcato** [comment]
@doom369, @blynkkk I'm glad to announce the first usable version of the homebridge-blynk plugin. Please have a try and ask Siri to "turn on the computer" !

**Comment by doom369** [comment]
Nice!

**Comment by blynkkk** [comment]
super cool! thanks! :pray: 
Will test it out on a weekend.

@ilcato Do you have a "getting started" somewhere?

**Comment by ilcato** [comment]
@blynkkk, basically:
- select a platform on which to install the plugin (I'm using a Raspberry, but any platform that support node.js may be adopted)
- install homebridge (follow instruction) on https://www.npmjs.com/package/homebridge
- install the blynk homebridge plugin: sudo npm install -g homebridge-blynk
- create a config.json file in the .homebridge directory of the user that run homebridge (see example in https://github.com/ilcato/homebridge-blynk/blob/master/config.json)
- run homebridge (and create an autostart file on the hosted platform)

For the config file:
- specify credentials and dashboard name of an existing dashboard on the referred local Blynk server
- assuming a switch within the dashboard specify in the accessories parameter of the config.json file:

`{
                    "name":         "SwitchD5",
                    "widget":       "Switch",
                    "mode":         "SWITCH",
                    "caption":      "Lamp 1",
                    "pin":          "D5"
                }`

where:
- name will be the accessory name from the HomeKit point of view
- widget must be "Switch"
- mode can be "SWITCH" or "PUSH"
- caption will be the name you should refer to from Siri
- pin is the board pin connected to the switch

Use an HomeKit app to add the accessory to the iPhone/iPad, e.g.: [MyHome](https://itunes.apple.com/it/app/myhome-app/id1054351812?l=en&mt=8) 

After that you can say to Siri:

turn on lamp 1

**Comment by blynkkk** [comment]
just noticed the instructions. Will post it soon. Thanks

**Comment by ilcato** [comment]
@blynkkk, what did you tested? only a switch or also contact sensor and temperature sensor.
What kind of other services do you think can be useful to add?

**Comment by blynkkk** [comment]
I haven't tested it yet, but I will do this week and would be happy to provide feedback.

**Comment by blynkkk** [comment]
@ilcato I was able to run it successfully. Thanks!
I just don't know how to ask siri about the temperature and about contact sensor :)

Also, could you explain the naming of accessories. 
Looks like I can only name them:

```
"Switch{pin}"
```

Is it true for other types like `"ContactSensor1"` and `"TemperatureSensor1"` ? Can I only use these names?

**Comment by ilcato** [comment]
@blynkkk, you can "name" it whatever you want. The "caption" field is the one recognized by Siri.
Regarding querying via Siri about a temperature value you can ask it directly: provided the caption of the temperature sensor is for example "Sensor A" you can ask: whats the temperature of Sensor A?
If you assign the temperature accessory to a room (for example to the kitchen room) you can ask: what's the kitchen temperature?
See [this](https://support.apple.com/en-us/HT204893).

**Comment by blynkkk** [comment]
Thanks for the link! it makes more sense now. There are still a couple of questions, though:
- I wasn't able to get the temperature from the sensor. In Terminal I see:

``` cpp
[4/8/2016, 12:55:31 PM] [Blynk] There was a problem sending hardware read command on: V27 - Hardware timeout: vr27
```
- How to ask Siri about the Contact sensor? Let's say it's name is "Front Door". 
  What should be asked: "What's the status of Front Door" or "Check if Front Door is locked"

You asked about what other commands could be. I've checked what our users do and here are couple of ideas. Is it possible to make more generic requests like:
- "Siri, what's the level of {Widget}" . e.g. What's the level of Humidity / water tank. Reply with some value.
- "Siri," set {Widget} to {value} . E.g. Set Thermostat to 25
- "Siri, what's the status of {Widget}". Can siri reply smth like "it's ON".  For example: 
  
  > – Siri, what's the status of Alarm. 
  > – Alarm is ON, sir  

I'm just checking what's possible. We would be happy to integrate Blynk deeper with your plugin. I will also create a tutorial and shoot a video.

UPD:
just found this: https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js

**Comment by ilcato** [comment]
@blynkkk: let's try to respond:
- for the error in the log: it shows a problem in not receiving the response from the server. I need more info about your configuration and device in order to support you.
- for querying the front door sensor I don't think it is possible now. The Siri command that you can send to HomeKit are strictly controlled by Apple and cannot be set by a developer or a user. Apple is constantly adding new capabilities (working on the cloud part of the system) even without upgrading iOs. For example they added Siri support to the blind/windows covering service without any public communications. I found it trying periodically. The link I send you is the only public information existing but it is not completely updated. Some times the Apple service is not completely reliable: you try one command/query, the voice to text works but the semantic is not catched; you retry immediately and it works with the same captured text. It also depends on the Language that you set in Siri.
- The queries you suggested should work as soon as I implement the corresponding accessories, this is the reason why I asked for a priority. For example, you can set the level of the temperature of a thermostat but I need to implement in the plugin a mapping between HomeKit and Blynk and since Blynk define only "technical" widget and not "semantic" one we need to define a "standard" mapping. Currently I implemented only "Switch", "Contact Sensor" and "Temperature Sensor" HomeKit accessories types (aka services" in HomeKit language). I mapped the Temperature Sensor to a read operation on the corresponding pin that you can configure in config.json, but you must provide to the pin (hardware or virtual) the value in the right range. We can discuss together how to define such a mapping.
- The link you found represent the list of possible accessories/services that we can insert into the plugin. The HAP-NodeJs is the core engine of homebridge so the complete technology stack of the solution is: homebridge-blynk --> homebridge --> HAP-NodeJS. I'm already using the types defined in the file and simply will add other elements for supporting other capabilities in Blynk.

**Comment by blynkkk** [comment]
Hi @ilcato 

> for the error in the log: it shows a problem in not receiving the response from the server. I need more info about your configuration and device in order to support you.

Here is my config.json:

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file.",

    "platforms": [
            {
            "platform": "Blynk",
            "name": "Blynk",
            "server": "cloud.blynk.cc",
            "appPort": "8443",
            "username": "*******",
            "password": "*******",
            "dashboardName": "Blynk Demo",
            "accessories": [
                {
                    "name":         "SwitchV0",
                    "widget":       "Switch",
                    "mode":         "SWITCH",
                    "caption":      "Bedroom lights",
                    "pin":          "D7"
                },
                {
                    "name":         "ContactSensor1",
                    "widget":       "ContactSensor",
                    "caption":      "Bedroom Door",
                    "pin":          "V4"
                },
                {
                    "name":         "TemperatureSensor1",
                    "widget":       "TemperatureSensor",
                    "caption":      "Bedroom Sensor",
                    "pin":          "V27"
                }
            ]
        }
    ],
    "accessories": [
    ]
}
```

here is what terminal shows:

```
[4/12/2016, 9:40:41 PM] Loaded plugin: homebridge-blynk
[4/12/2016, 9:40:41 PM] Registering platform 'homebridge-blynk.Blynk'
[4/12/2016, 9:40:41 PM] ---
[4/12/2016, 9:40:42 PM] Loaded plugin: homebridge-ifttt
[4/12/2016, 9:40:42 PM] Registering platform 'homebridge-ifttt.IFTTT'
[4/12/2016, 9:40:42 PM] ---
[4/12/2016, 9:40:42 PM] Loaded plugin: homebridge-people
[4/12/2016, 9:40:42 PM] Registering accessory 'homebridge-people.people'
[4/12/2016, 9:40:42 PM] ---
[4/12/2016, 9:40:42 PM] Loaded config.json with 0 accessories and 1 platforms.
[4/12/2016, 9:40:42 PM] ---
[4/12/2016, 9:40:42 PM] Loading 1 platforms...
[4/12/2016, 9:40:42 PM] [Blynk] Initializing Blynk platform...
[4/12/2016, 9:40:42 PM] [Blynk] Loading accessories...
[4/12/2016, 9:40:42 PM] Loading 0 accessories...
[4/12/2016, 9:40:43 PM] [Blynk] Found: SwitchV0
[4/12/2016, 9:40:43 PM] [Blynk] Found: ContactSensor1
[4/12/2016, 9:40:43 PM] [Blynk] Found: TemperatureSensor1
[4/12/2016, 9:40:43 PM] [Blynk] Initializing platform accessory 'SwitchV0'...
[4/12/2016, 9:40:43 PM] [Blynk] Initializing platform accessory 'ContactSensor1'...
[4/12/2016, 9:40:43 PM] [Blynk] Initializing platform accessory 'TemperatureSensor1'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     

[4/12/2016, 9:40:43 PM] Homebridge is running on port 51826.
[4/12/2016, 9:41:03 PM] [Blynk] There was a problem sending hardware read command on: V27 - Hardware timeout: vr27
[4/12/2016, 9:41:15 PM] [Blynk] There was a problem sending hardware read command on: V27 - Hardware timeout: vr27
[4/12/2016, 9:41:27 PM] [Blynk] There was a problem sending hardware read command on: V27 - Hardware timeout: vr27
```

Since I can control D7 - I assume that connection is established and it's working.

**Comment by blynkkk** [comment]
> for querying the front door sensor I don't think it is possible now.

Sorry for confusion, I just can't find a phrase to say to Siri to get the information from `ContactSensor` :)

> The queries you suggested should work as soon as I implement the corresponding accessories...

I've quickly went through the accessories and picked what's relevant to Blynk. It's very subjective. You can definitely use your own judgement. 

1st priority:
.TemperatureSensor
.HumiditySensor
.MotionSensor
.SmokeSensor
.LightSensor
.GarageDoorOpener
.Brightness
.On (not sure what's that)
.Lightbulb
.Outlet

Rest:
.BatteryLevel
.Hue
.Saturation
.Door
.Window
.Fan
.Thermostat
.LeakSensor
.CurrentRelativeHumidity
.CurrentTemperature
.CurrentAmbientLightLevel
.CurrentHeatingCoolingState

Whenever you have time that would be cool to have. 
Thanks for all your contributions!

**Comment by ilcato** [comment]
@blynkkk, are you using the cloud server (cloud.blynk.cc) in your test?
Because I tested it without success and @doom369 told me that the cloud server makes an strongest authentication  on port 8443 (client certificate).

**Comment by doom369** [comment]
@ilcato it is not related to server this is something with read command. Probably within your code.

**Comment by blynkkk** [comment]
@ilcato Yes, I'm using cloud.blynk.cc, and since I can trigger D7 successfully, I assume that everything should work. But reading is not working.

**Comment by ilcato** [comment]
@blynkkk, did you create into the Dashboard/Project "Blynk Demo” a widget attached to V27?

**Comment by blynkkk** [comment]
@ilcato Yes, there is a Value Display widget on V27. Hardware is pushing temperature there every 2 seconds and I can see it in the project

**Comment by ilcato** [comment]
@blynkkk, try the following test script. It access the low level library I developed (blynk-app-client).

[getV27.js.zip](https://github.com/ilcato/homebridge-blynk/files/224881/getV27.js.zip)

**Comment by ilcato** [comment]
@blynkkk , where you able to test the script?

**Comment by miliante** [comment]
Hello @ilcato. Great extension to Homebridge!

Nevertheless, I am having the same problem as @blynkkk. I can't read from Virtual Pin, in my case, 11.
`[6/20/2016, 7:20:35 PM] [Blynk] There was a problem sending hardware read command on: V11 - Hardware timeout: vr10`
Same configuration as him, but with a local server. Blink app on iPhone works normally and shows me the temperature and its history.

I tried also getV27.js.zip, replacing the: username, password, dashboard name and `return blynk.hardware(dashboard.id, "v", "r", 11);`. It finds the dashboard and its id, but returns nothing.

**Comment by miliante** [comment]
I made it work (partially) by replacing a routine in index.js with the REST API probing the server. For now my data is hardcoded but I will make it more general later. (perhaps add humidity also).

**Comment by ilcato** [comment]
Can you make a pull request?
