### ISSUE TITLE
I have exactly the same problem

### ISSUE THREAD

**Issue by GogaPit** [ilcato/homebridge-blynk#19]
https://github.com/nfarina/homebridge/issues/1916#issue-335600765

**Comment by ilcato** [comment]
See the release notes and usage notes:

_Works on both cloud server and local server: for cloud server the Blynk App must be running in order to receive automatic update of the pin values (setting pins works also without the app runing); for local server put "allow.reading.widget.without.active.app=true" in server.properties in order to be able to receive automatic update of the pin values._
